### ISSUE TITLE
‏​

### ISSUE THREAD

**Issue by TatleCat** [koishijs/koishi-plugin-click-colorful#1]
你有没有想过会有
铸币的安卓用户下载这个

启用之后啥也点不了
耗费两小时时间成本搞好了
要长按, 然后再停, 再长按反复几十次
才能触发一次按键互动 [除了数值]
最后把粒子数量改为0才能关掉然后删除

还好你把选项放在通用设置栏了
要不然就因为你这个插件废了>:(

**Comment by CyanChanges** [comment]
没有想过，koishi-android 似乎没有人用，没人测试哈，感谢您的身先士卒哈
那你活该，我和你说啊，再多骂一下就会爆炸
点不了我也没办法，这个可能是 Chromium 手机优化的特性，请尝试先反馈至 Chromium 的，亲
对此我表示十分的痛心，并建议你装 k234-security，能解决所有
webui 网页点击失效不影响 Koishi 运行，Koishi跑跑得好好的那里废了？
卸载插件可以修改 koishi.yml
你想用就用，Koishi 不对非官方插件负责，
你可以去自己建立 websocket 连接 console，影响没有一点
所以 shigma 怎么你了

**Comment by TatleCat** [comment]
没有想攻击你的意思,我也自嘲铸币了
   只是想吐槽一下  (((

**Comment by TatleCat** [comment]
没有想刻意攻击你的意思
我也自嘲铸币了, 只是想吐槽一下 (((

**Comment by shigma** [comment]
确实没考虑移动端的情况，我想想办法，比如加个 throttle 应该能缓解卡顿。

**Comment by CyanChanges** [comment]
> 确实没考虑移动端的情况，我想想办法，比如加个 throttle 应该能缓解卡顿。

主要是 div 把下面东西挡住了吧，想办法不遮挡应该就好了

**Comment by shigma** [comment]
遮挡问题加个 pointer-events none 就行

**Comment by shigma** [comment]
所以是遮挡问题而不是卡顿吗……看这个问题描述完全看不出来

**Comment by TatleCat** [comment]
> 所以是遮挡问题而不是卡顿吗……看这个问题描述完全看不出来

是的 π_π

**Comment by CyanChanges** [comment]
> 所以是遮挡问题而不是卡顿吗……看这个问题描述完全看不出来

因为看着像触发不到下面组件的 event。。。

> "要长按, 然后再停, 再长按反复几十次
才能触发一次按键互动 [除了数值]"

**Comment by shigma** [comment]
更新了 1.2.0，请试试看。

**Comment by TatleCat** [comment]
谢谢, 是我语急了, 果咩馁 _(._.)_
